In [102]:
import pandas as pd
import numpy as np
from datetime import datetime
import time
from dateutil.parser import parse

In [103]:
train=pd.read_csv("/Users/Wei/Google Drive/Bentley/S3 MA710 Data mining/Data Mining group work/Final project/Google analytics data/train_all.csv")

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (3,50) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [104]:
test=pd.read_csv("/Users/Wei/Google Drive/Bentley/S3 MA710 Data mining/Data Mining group work/Final project/Google analytics data/test_all.csv")

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [105]:
train=train.iloc[:,1:]
train.head()

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,browser,browserSize,...,adwordsClickInfo.isVideoAd,adwordsClickInfo.page,adwordsClickInfo.slot,campaign,campaignCode,isTrueDirect,keyword,medium,referralPath,source
0,Organic Search,20160902,1131660440785968503,1131660440785968503_1472830385,Not Socially Engaged,1472830385,1,1472830385,Chrome,not available in demo dataset,...,NaN,NaN,NaN,(not set),NaN,NaN,(not provided),organic,NaN,google
1,Organic Search,20160902,377306020877927890,377306020877927890_1472880147,Not Socially Engaged,1472880147,1,1472880147,Firefox,not available in demo dataset,...,NaN,NaN,NaN,(not set),NaN,NaN,(not provided),organic,NaN,google
2,Organic Search,20160902,3895546263509774583,3895546263509774583_1472865386,Not Socially Engaged,1472865386,1,1472865386,Chrome,not available in demo dataset,...,NaN,NaN,NaN,(not set),NaN,NaN,(not provided),organic,NaN,google
3,Organic Search,20160902,4763447161404445595,4763447161404445595_1472881213,Not Socially Engaged,1472881213,1,1472881213,UC Browser,not available in demo dataset,...,NaN,NaN,NaN,(not set),NaN,NaN,google + online,organic,NaN,google
4,Organic Search,20160902,27294437909732085,27294437909732085_1472822600,Not Socially Engaged,1472822600,2,1472822600,Chrome,not available in demo dataset,...,NaN,NaN,NaN,(not set),NaN,True,(not provided),organic,NaN,google

In [106]:
test=test.iloc[:,1:]
test.head()

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,browser,browserSize,...,adwordsClickInfo.gclId,adwordsClickInfo.isVideoAd,adwordsClickInfo.page,adwordsClickInfo.slot,campaign,isTrueDirect,keyword,medium,referralPath,source
0,Organic Search,20171016,6167871330617112363,6167871330617112363_1508151024,Not Socially Engaged,1508151024,2,1508151024,Chrome,not available in demo dataset,...,NaN,NaN,NaN,NaN,(not set),True,(not provided),organic,NaN,google
1,Organic Search,20171016,0643697640977915618,0643697640977915618_1508175522,Not Socially Engaged,1508175522,1,1508175522,Chrome,not available in demo dataset,...,NaN,NaN,NaN,NaN,(not set),NaN,(not provided),organic,NaN,google
2,Organic Search,20171016,6059383810968229466,6059383810968229466_1508143220,Not Socially Engaged,1508143220,1,1508143220,Chrome,not available in demo dataset,...,NaN,NaN,NaN,NaN,(not set),NaN,(not provided),organic,NaN,google
3,Organic Search,20171016,2376720078563423631,2376720078563423631_1508193530,Not Socially Engaged,1508193530,1,1508193530,Safari,not available in demo dataset,...,NaN,NaN,NaN,NaN,(not set),NaN,(not provided),organic,NaN,google
4,Organic Search,20171016,2314544520795440038,2314544520795440038_1508217442,Not Socially Engaged,1508217442,1,1508217442,Safari,not available in demo dataset,...,NaN,NaN,NaN,NaN,(not set),NaN,(not provided),organic,NaN,google

In [58]:
train.columns, train.shape

(Index(['channelGrouping', 'date', 'fullVisitorId', 'sessionId',
        'socialEngagementType', 'visitId', 'visitNumber', 'visitStartTime',
        'browser', 'browserSize', 'browserVersion', 'deviceCategory',
        'flashVersion', 'isMobile', 'language', 'mobileDeviceBranding',
        'mobileDeviceInfo', 'mobileDeviceMarketingName', 'mobileDeviceModel',
        'mobileInputSelector', 'operatingSystem', 'operatingSystemVersion',
        'screenColors', 'screenResolution', 'city', 'cityId', 'continent',
        'country', 'latitude', 'longitude', 'metro', 'networkDomain',
        'networkLocation', 'region', 'subContinent', 'bounces', 'hits',
        'newVisits', 'pageviews', 'transactionRevenue', 'visits', 'adContent',
        'adwordsClickInfo.adNetworkType', 'adwordsClickInfo.criteriaParameters',
        'adwordsClickInfo.gclId', 'adwordsClickInfo.isVideoAd',
        'adwordsClickInfo.page', 'adwordsClickInfo.slot', 'campaign',
        'campaignCode', 'isTrueDirect', 'keyword', 'medium', 'referralPath',
        'source'],
       dtype='object'), (903653, 55))

In [107]:
cols=["socialEngagementType", "browserSize","browserVersion","flashVersion","language","mobileDeviceBranding",
"mobileDeviceInfo","mobileDeviceMarketingName","mobileDeviceModel","mobileInputSelector","socialEngagementType",
"browserSize","browserVersion","flashVersion","operatingSystemVersion","screenColors","screenResolution",
"cityId","latitude","longitude","networkLocation","adwordsClickInfo.criteriaParameters","adContent","adwordsClickInfo.adNetworkType",
"adwordsClickInfo.gclId","adwordsClickInfo.isVideoAd","adwordsClickInfo.page","adwordsClickInfo.slot","campaign","campaignCode"]

In [108]:
len(cols)

30

In [109]:
train_new=train.drop(cols, axis=1)

In [110]:
test_new=test.drop(cols[:29],axis=1)

In [111]:
train_new.shape, test_new.shape

((903653, 29), (804684, 28))

In [112]:
train_new.head().T

,0,1,2,3,4
channelGrouping,Organic Search,Organic Search,Organic Search,Organic Search,Organic Search
date,20160902,20160902,20160902,20160902,20160902
fullVisitorId,1131660440785968503,377306020877927890,3895546263509774583,4763447161404445595,27294437909732085
sessionId,1131660440785968503_1472830385,377306020877927890_1472880147,3895546263509774583_1472865386,4763447161404445595_1472881213,27294437909732085_1472822600
visitId,1472830385,1472880147,1472865386,1472881213,1472822600
visitNumber,1,1,1,1,2
visitStartTime,1472830385,1472880147,1472865386,1472881213,1472822600
browser,Chrome,Firefox,Chrome,UC Browser,Chrome
deviceCategory,desktop,desktop,desktop,desktop,mobile
isMobile,False,False,False,False,True
operatingSystem,Windows,Macintosh,Windows,Linux,Android
city,Izmir,not available in demo dataset,Madrid,not available in demo dataset,not available in demo dataset
continent,Asia,Oceania,Europe,Asia,Europe
country,Turkey,Australia,Spain,Indonesia,United Kingdom
metro,(not set),not available in demo dataset,(not set),not available in demo dataset,not available in demo dataset
networkDomain,ttnet.com.tr,dodo.net.au,unknown.unknown,unknown.unknown,unknown.unknown
region,Izmir,not available in demo dataset,Community of Madrid,not available in demo dataset,not available in demo dataset
subContinent,Western Asia,Australasia,Southern Europe,Southeast Asia,Northern Europe
bounces,1,1,1,1,1
hits,1,1,1,1,1
newVisits,1,1,1,1,NaN
pageviews,1,1,1,1,1
transactionRevenue,NaN,NaN,NaN,NaN,NaN
visits,1,1,1,1,1
isTrueDirect,NaN,NaN,NaN,NaN,True
keyword,(not provided),(not provided),(not provided),google + online,(not provided)
medium,organic,organic,organic,organic,organic
referralPath,NaN,NaN,NaN,NaN,NaN
source,google,google,google,google,google

### Transaction revenue filling na

In [119]:
train_new["trans_revenue"]=[np.log(i) for i in train.transactionRevenue]

In [117]:
train.trans_revenue.isna().sum(), len(train.trans_revenue), round((1-train.trans_revenue.isna().sum()/len(train.trans_revenue))*100,2)

(892138, 903653, 1.27)

In [66]:
train_new.bounces.isna().sum(), train_new.newVisits.isna().sum()

(453023, 200593)

In [67]:
train_new.isTrueDirect.isna().sum(), train_new.isMobile.isna().sum()

(629648, 0)

In [120]:
train_new[["trans_revenue","bounces","newVisits","isTrueDirect"]]=train_new[["trans_revenue","bounces","newVisits","isTrueDirect"]].fillna(value=0)
test_new[["bounces","newVisits","isTrueDirect"]]=test_new[["bounces","newVisits","isTrueDirect"]].fillna(value=0)

### Turning date to year and month

In [123]:
train_new["month"]=[str(i)[4:6] for i in train.date]
train_new["year"]=[str(i)[:4] for i in train.date]

In [124]:
test_new["month"]=[str(i)[4:6] for i in test.date]
test_new["year"]=[str(i)[:4] for i in test.date]

Changing date

In [125]:
train_new["date1"]=[parse(str(i)[4:6]+"/"+str(i)[6:]+"/"+str(i)[:4]) for i in train.date]

In [126]:
test_new["date1"]=[parse(str(i)[4:6]+"/"+str(i)[6:]+"/"+str(i)[:4]) for i in test.date]

In [127]:
date={6:"1. Sunday",5:"7. Saturday",4:"6. Friday",3:"5. Thursday",2:"4. Wednesday",1:"3. Tuesday",0:"2. Monday"}

In [128]:
train_new["week_day"]=[date[datetime.weekday(i)] for i in train_new.date1]

In [129]:
test_new["week_day"]=[date[datetime.weekday(i)] for i in test_new.date1]

In [130]:
test_new.week_day.unique()

array(['2. Monday', '5. Thursday', '1. Sunday', '6. Friday',
       '7. Saturday', '4. Wednesday', '3. Tuesday'], dtype=object)

In [131]:
train_new.head()

,channelGrouping,date,fullVisitorId,sessionId,visitId,visitNumber,visitStartTime,browser,deviceCategory,isMobile,...,isTrueDirect,keyword,medium,referralPath,source,trans_revenue,month,year,date1,week_day
0,Organic Search,20160902,1131660440785968503,1131660440785968503_1472830385,1472830385,1,1472830385,Chrome,desktop,False,...,0,(not provided),organic,NaN,google,0.0,09,2016,2016-09-02,6. Friday
1,Organic Search,20160902,377306020877927890,377306020877927890_1472880147,1472880147,1,1472880147,Firefox,desktop,False,...,0,(not provided),organic,NaN,google,0.0,09,2016,2016-09-02,6. Friday
2,Organic Search,20160902,3895546263509774583,3895546263509774583_1472865386,1472865386,1,1472865386,Chrome,desktop,False,...,0,(not provided),organic,NaN,google,0.0,09,2016,2016-09-02,6. Friday
3,Organic Search,20160902,4763447161404445595,4763447161404445595_1472881213,1472881213,1,1472881213,UC Browser,desktop,False,...,0,google + online,organic,NaN,google,0.0,09,2016,2016-09-02,6. Friday
4,Organic Search,20160902,27294437909732085,27294437909732085_1472822600,1472822600,2,1472822600,Chrome,mobile,True,...,True,(not provided),organic,NaN,google,0.0,09,2016,2016-09-02,6. Friday

VisitStartTime

In [132]:
train_new["visit_start"]=[datetime.utcfromtimestamp(i) for i in train_new.visitStartTime]

In [133]:
test_new["visit_start"]=[datetime.utcfromtimestamp(i) for i in test_new.visitStartTime]

In [134]:
train_new["visit_hour"]=[i.hour for i in train_new.visit_start]
test_new["visit_hour"]=[i.hour for i in test_new.visit_start]

Sourcess

In [135]:
sources=[]
for i in train_new.source:
    if "facebook" in i:
        sources.append("facebook")
    elif "googleplex" in i:
        sources.append("googleplex")
    elif "mail.google" in i:
        sources.append("google_mail")
    elif "youtube" in i:
        sources.append("youtube")
    elif "quora" in i:
        sources.append("quora")
    elif "yahoo" in i:
        sources.append("yahoo")
    elif "reddit" in i:
        sources.append("reddit")
    elif "baidu" in i:
        sources.append("baidu")
    elif "bing" in i:
        sources.append("bing")
    elif "(direct)" in i:
        sources.append("direct")
    elif "qiita" in i:
        sources.append("qiita")
    elif "sashihara" in i:
        sources.append("sashihara")
    elif "businessinsider" in i:
        sources.append("businessinsider")
    elif "yandex" in i:
        sources.append("yandex")
    elif "golang" in i:
        sources.append("golang")
    elif "Partners" in i:
        sources.append("Partners")
    elif "dfa" in i:
        sources.append("dfa")
    elif "lunametrics" in i:
        sources.append("lunametrics")
    elif "ask" in i:
        sources.append("ask")
    elif ".edu" in i:
        sources.append("edu")
    elif "google" in i:
        sources.append("google")
    else:
        sources.append("others")

In [136]:
train_new["sources"]=sources

In [137]:
sourcest=[]
for i in test_new.source:
    if "facebook" in i:
        sourcest.append("facebook")
    elif "googleplex" in i:
        sourcest.append("googleplex")
    elif "mail.google" in i:
        sourcest.append("google_mail")
    elif "youtube" in i:
        sourcest.append("youtube")
    elif "quora" in i:
        sourcest.append("quora")
    elif "yahoo" in i:
        sourcest.append("yahoo")
    elif "reddit" in i:
        sourcest.append("reddit")
    elif "baidu" in i:
        sourcest.append("baidu")
    elif "bing" in i:
        sourcest.append("bing")
    elif "(direct)" in i:
        sourcest.append("direct")
    elif "qiita" in i:
        sourcest.append("qiita")
    elif "sashihara" in i:
        sourcest.append("sashihara")
    elif "businessinsider" in i:
        sourcest.append("businessinsider")
    elif "yandex" in i:
        sourcest.append("yandex")
    elif "golang" in i:
        sourcest.append("golang")
    elif "Partners" in i:
        sourcest.append("Partners")
    elif "dfa" in i:
        sourcest.append("dfa")
    elif "lunametrics" in i:
        sourcest.append("lunametrics")
    elif "ask" in i:
        sourcest.append("ask")
    elif ".edu" in i:
        sourcest.append("edu")
    elif "google" in i:
        sourcest.append("google")
    else:
        sourcest.append("others")

In [138]:
test_new["sources"]=sourcest

Browsers

In [141]:
browser=[]
for i in test_new.browser:
    if "firefox" in i.lower():
        browser.append("Firefox")
    elif "mozilla" in i.lower():
        browser.append("Firefox")
    elif "chrome" in i.lower():
        browser.append("Chrome")
    elif "internet explorer" in i.lower():
        browser.append("Internet Explorer")
    elif "safari" in i.lower():
        browser.append("Safari")
    elif "opera" in i.lower():
        browser.append("Opera")
    elif "edge" in i.lower():
        browser.append("Edge")
    elif "amazon" in i.lower():
        browser.append("Amazon")
    elif "maxthon" in i.lower():
        browser.append("Maxthon")
    elif "seznam" in i.lower():
        browser.append("Seznam")
    elif "nokia" in i.lower():
        browser.append("Nokia")
    elif "android" in i.lower():
        browser.append("Android")
    elif "puffin" in i.lower():
        browser.append("Puffin")
    elif "coc coc" in i.lower():
        browser.append("Coc Coc")
    elif "yabrowser" in i.lower():
        browser.append("YaBrowser")
    elif "changa" in i.lower():
        browser.append("Changa")
    elif "ye" in i.lower():
        browser.append("YE")
    elif "apple" in i.lower():
        browser.append("Apple")
    else:
        browser.append("Others")

In [142]:
test_new["browser_new"]=browser

In [140]:
train_new["browser_new"]=browser

In [143]:
test_new.operatingSystem.unique()

array(['Macintosh', 'Windows', 'iOS', 'Linux', 'Android', 'Chrome OS',
       '(not set)', 'Windows Phone', 'Samsung', 'Tizen',
       'Playstation Vita', 'OS/2', 'Xbox', 'Nintendo 3DS', 'BlackBerry',
       'Nintendo WiiU', 'SymbianOS', 'Firefox OS', 'FreeBSD', 'OpenBSD',
       'SunOS', 'Nokia'], dtype=object)

In [144]:
train_new.columns

Index(['channelGrouping', 'date', 'fullVisitorId', 'sessionId', 'visitId',
       'visitNumber', 'visitStartTime', 'browser', 'deviceCategory',
       'isMobile', 'operatingSystem', 'city', 'continent', 'country', 'metro',
       'networkDomain', 'region', 'subContinent', 'bounces', 'hits',
       'newVisits', 'pageviews', 'transactionRevenue', 'visits',
       'isTrueDirect', 'keyword', 'medium', 'referralPath', 'source',
       'trans_revenue', 'month', 'year', 'date1', 'week_day', 'visit_start',
       'visit_hour', 'sources', 'browser_new'],
      dtype='object')

In [145]:
columnss=["visitStartTime","source","browser","referralPath","date","keyword","metro","networkDomain"]

In [146]:
train_new=train_new.drop(columnss, axis=1)
test_new=test_new.drop(columnss, axis=1)

In [147]:
tf={True:1,False:0}

In [148]:
train_new.isMobile=[tf[i] for i in train_new.isMobile]
test_new.isMobile=[tf[i] for i in test_new.isMobile]

In [149]:
tf={True:1,False:0,0:0}

In [150]:
train_new["isTrueDirect"]=[tf[i] for i in train_new.isTrueDirect]

In [151]:
test_new["isTrueDirect"]=[tf[i] for i in test_new.isTrueDirect]

In [153]:
train_new.to_csv("/Users/Wei/Google Drive/Bentley/S3 MA710 Data mining/Data Mining group work/Final project/Google analytics data/clean_train.csv")

In [154]:
test_new.to_csv("/Users/Wei/Google Drive/Bentley/S3 MA710 Data mining/Data Mining group work/Final project/Google analytics data/clean_test.csv")

In [155]:
train_new.shape, test_new.shape

((903653, 30), (804684, 28))

In [188]:
train_new.operatingSystem.unique()

array(['Windows', 'Macintosh', 'Linux', 'Android', 'iOS', 'Chrome OS',
       'BlackBerry', '(not set)', 'Samsung', 'Windows Phone', 'Xbox',
       'Nintendo Wii', 'Firefox OS', 'Nintendo WiiU', 'FreeBSD', 'Nokia',
       'NTT DoCoMo', 'Nintendo 3DS', 'SunOS', 'OpenBSD'], dtype=object)

In [157]:
test_new.year.unique()

array(['2017', '2018'], dtype=object)

In [158]:
test_new.visitNumber.unique()

array([  2,   1,   6,   4,  22,   3,  17,  18,   5,  10,  14,   8, 102,
        15,  36,  54,  11,  30,  20, 100,  46, 101,  99,   7, 138,  16,
        13,  24,   9,  21,  34,  28,  12,  29,  33,  39,  19,  57,  45,
        27,  43,  25,  26,  31,  23,  98, 149,  35,  72, 124,  69,  93,
        50,  64,  94,  70,  38, 148,  42, 158,  82, 159, 125,  88,  48,
        55,  63,  66, 401,  49,  58, 137,  40,  56,  65,  60,  59,  41,
       155,  90, 112, 136,  32, 126, 143,  51,  52, 183,  73, 184,  68,
       169,  47,  86,  87,  89,  92,  96,  97,  91,  85, 160,  44,  78,
       163, 147, 150, 235, 113, 164, 223, 222,  76,  53,  77, 128,  81,
       129, 106, 192, 193, 175, 152, 324, 161, 181, 273, 272, 208, 287,
       104,  84, 133,  37, 146, 118,  62, 122,  71, 114, 115, 131,  61,
       130,  83, 396, 232, 134, 202, 132, 121, 120, 107, 135, 204, 205,
       207,  79, 206, 369,  80,  75, 400, 264, 265, 105, 172, 173, 174,
       258, 456, 127, 403, 402, 404, 151,  74, 171, 440, 108,  95, 215,
       453, 452,  67, 154, 316, 317, 117, 168, 119, 392, 299, 109, 110,
       140, 162, 198, 363, 280, 281, 221, 220, 448, 302, 297, 447, 188,
       386, 387, 116, 153, 203, 413, 123, 191, 228, 227, 142, 381, 263,
       391, 139, 194, 195, 260, 259, 441, 111, 156, 408, 145, 186, 157,
       234, 233, 167, 420, 421, 103, 237, 141, 338, 170, 236, 424, 425,
       423, 422, 224, 449, 450, 313, 176, 177, 457, 225, 197, 196, 182,
       179, 245, 432, 241, 218, 256, 189, 255, 385, 262, 443, 445, 266,
       362, 361, 360, 303, 357, 226, 380, 416, 209, 210, 213, 214, 212,
       295, 296, 211, 293, 294, 320, 166, 165, 219, 311, 354, 355, 240,
       312, 356, 407, 414, 185, 418, 275, 274, 247, 248, 371, 370, 242,
       243, 244, 144, 346, 344, 345, 199, 455, 428, 429, 383, 353, 261,
       201, 270, 190, 397, 178, 388, 415, 309, 286, 285, 284, 333, 334,
       335, 332, 187, 246, 398, 180, 238, 267, 298, 217, 216, 412, 290,
       229, 306, 366, 368, 365, 200, 364, 367, 257, 454, 337, 330, 329,
       331, 271, 419, 230, 350, 349, 318, 250, 253, 252, 251, 431, 430,
       411, 410, 269, 268, 375, 378, 379, 373, 374, 358, 433, 434, 417,
       389, 390, 249, 315, 314, 328, 327, 343, 439, 438, 442, 239, 372,
       437, 436, 435, 359, 399, 300, 405, 384, 336, 305, 444, 276, 277,
       406, 310, 231, 307, 308, 292, 291, 254, 301, 323, 322, 321, 319,
       427, 426, 288, 289, 304, 409, 382, 283, 282, 451, 278, 279, 342,
       339, 340, 341, 446])

In [163]:
a=train[["fullVisitorId","country","sessionId"]].groupby(["fullVisitorId","country"]).count()

In [164]:
a.reset_index(level=0, inplace=True)

In [166]:
b=a.groupby(["fullVisitorId"]).count()

In [191]:
a

                      fullVisitorId  sessionId
country
China                 4823595352351          1
United States         5103959234087          1
New Zealand          10278554503158          1
Peru                 20424342248747          1
United Kingdom       26722803385797          1
United States        27376579751715          1
Turkey               33471059618621          1
United States        35794135966385          1
Brazil               39460501403861          1
United States        40862739425590          2
United States        45417921646651          1
France               47810105303746          1
Peru                 48421062322244          1
Pakistan             52246474382344          1
Japan                58970809397690          1
Australia            61609983499251          1
Brazil               62267706107999          1
Japan                62349695125717          1
Russia               63834990385751          1
Philippines          64767209884626          2
United States        68403966359845          1
United Kingdom       72202462202136          1
Netherlands          75746323734481          1
United States        77980744724824          1
United States        82001414223176          1
United States        85059828173212          1
United States        90085033332104          1
Belgium              90134415725564          1
United States        93957001069502          1
France               95855025602688          1
...                             ...        ...
United States   9993293961944331752          1
(not set)       9993447781413571788          1
Brazil          9993684024735783106          1
United States   9993694779128450201          1
United States   9993701862089701718          1
United States   9994157350704454276          1
Japan           9994221968851351416          1
United States   9994287830486076662          1
Belgium         9994752083639387618          1
United States   9995055493309539077          1
Japan           9995884236248287794          1
United Kingdom  9996299359396130241          1
United States   9996436469769693414          1
United States    999662588290514293          1
Ireland         9996707176741780711          1
Vietnam         9996938340224171184          1
United Kingdom  9997442734352997421          1
Spain           9997536057704001970          1
United States   9997824979262110959          1
United States   9997962478838273085          1
Indonesia       9997988284201360522          1
Singapore        999814635208236250          1
Germany         9998392565533703052          1
United States   9998628427098906629          1
Thailand        9999355589118867468          1
Spain           9999470222842102470          1
Nigeria         9999493741609373843          1
India           9999607385222235728          1
United States   9999761280717362235          1
United Kingdom  9999963186378918199          1

[725758 rows x 2 columns]

In [182]:
c=b[b.sessionId>1]

In [175]:
r=train[["fullVisitorId","transactionRevenue"]].groupby(["fullVisitorId"]).sum()

In [186]:
t=pd.concat([c,r],axis=1, join="inner")
t[t.transactionRevenue>0]

                     sessionId  transactionRevenue
fullVisitorId
2871498069867123             3        9.635000e+07
61892085087294527            2        2.399000e+07
85830972238265715            2        8.687000e+07
134088266984701296           2        2.009000e+07
169337349809177349           2        6.115500e+08
188481372919586914           2        1.070400e+08
199390506505564850           2        8.031000e+08
200510094584379080           2        3.435000e+07
239011216868684634           2        4.479000e+07
263896833266166939           2        2.590000e+07
310411461029176203           3        3.518000e+07
327132720272185354           2        1.631000e+08
361534245405505016           2        1.396500e+08
382764578031539000           2        4.970500e+08
403029217967321711           2        4.572000e+07
422544802270284821           2        1.271300e+08
508002860985321055           2        1.369200e+08
517804428885255967           2        1.267900e+09
566233357235128805           2        7.913000e+07
596895434219823695           3        4.509100e+08
645131442954167518           2        4.077000e+07
730124493043113245           2        7.142000e+07
803888563485194008           2        1.895100e+08
848187910927716390           2        9.442000e+07
929967206775092152           2        2.800000e+06
934513430067402140           2        1.598000e+08
953889584295924240           2        1.872000e+07
1023615951662839630          3        2.583300e+08
1111470101899387454          2        3.846000e+07
1182594311076605554          2        3.348600e+08
...                        ...                 ...
7811787934602942622          2        1.400000e+07
7956245656986449961          2        5.022500e+08
8025955470222388064          2        3.359000e+07
8130967170149576800          2        1.497500e+08
8160024468956674004          2        1.391400e+08
8161117182595468101          2        4.261000e+07
8223058588270427668          2        5.039000e+07
8239665320308157318          2        4.292000e+07
8305324219354284523          2        7.967000e+07
8379929056656388083          2        5.999000e+07
8417202623298662742          2        2.718000e+07
8452979952112356529          2        5.097000e+07
8527647041260806312          2        3.358000e+07
8688274309849590379          2        5.696000e+07
8919336618754256169          2        3.468000e+08
8977039158734679466          2        9.676000e+07
9033474883204542086          2        1.598000e+07
9086408578145100131          2        1.071000e+08
9102289582475822657          2        2.171000e+08
9141220446851563090          2        5.845000e+07
9275740735751035515          3        6.399000e+08
9302767552528832368          2        1.257000e+08
9349161317881541522          2        1.259500e+08
9477829551781094415          2        5.599000e+07
9687976620185337812          2        1.159000e+07
9884208408379950496          2        1.949100e+08
9926655339980503224          2        3.228000e+07
9935363478089463685          2        2.901900e+08
9936682614369895259          2        4.013800e+08
9946704516426299877          2        2.687200e+08

[149 rows x 2 columns]

In [184]:
c.shape

(1881, 1)

In [181]:
r.shape

(723803, 1)